server:
  port: 39039
  base-url: "https://sonolus.untitledcharts.com"
  force-https: true
sonolus:
  required-client-version: 1.0.0
  items-per-page:
    default: 10
    engines: 10
  name: "UntitledCharts"
  description: "discord.gg/UntitledCharts\nA custom chart server :)"