server:
  port: 39039
  base-url: "https://untitledcharts.com"
  force-https: true
  debug: false
sonolus:
  required-client-version: 1.0.0
  items-per-page:
    default: 10
    engines: 10
  name: "UntitledCharts"
  # this description is a fallback if there is no locale string
  description: "discord.gg/UntitledCharts\nA custom chart server :)"
api:
  url: "http://127.0.0.1:39000"
  # Should match backend auth
  # Should not be given out
  auth: "..."
  auth-header: "..."